language: java

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java8-installer

services:
  - postgresql

before_script:
  - psql -c 'create database bastion;' -U postgres
  - cp config/database.yml.travis config/database.yml