language: java
jdk:
- oraclejdk8
addons:
  postgresql: '9.4'
  apt:
    packages:
    - oracle-java8-installer
services:
- postgresql
before_script:
- psql -c 'create database bastion;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: U2gXb/oEF60vDsqfPZtnhQoNl0sgCbP1Gn+BP4FHF1AqyMxI4W4RN9DqcLqQBipC5wcDbAipwNHwMBboVpjIv+24YRwVDK5AwZi9/2LvH+BWfdSs3B0Z1Yrj20z0DTpGSjoV8UAf9O0+ewHytGn2moQOmjEJsg86EI8HKWKfA6xjvX0HSa7fADDu5MFiO14i9XEAHQ3d6yZ3JN+X2xNSEV6qW9PRST9cqb9I2++iki0kXDNqzygPZtY+vQUB9ZnZVmWWS2p/6z7wuvhBYwARvuEBwaQXoqHsGkV73kF712Ypcw1SWWEzPqcOKR/0TjwaW8f7dfjIzpnWWQ2NKwQwxsJO2Z/Xe0XYWWQrdXRB6+DzDgVQuJd5CFy9/ZbJVJSax7acunf871FVf1RLSeW+LFwOl628qqEdRZg1hENnR8Qbrh4QxGk2hI5AW8otkjxuZtYVZKfgXNDksAZsbHK75HfyO4/Y22TnrjtbyzJHLrV3Wng61xzP3oIB35x1H29q8DwOoDQxMi7WtTbPgocbecwf6EnV3zCChHzXYSiaqBBaGQFQKhXAHY/WkJpUrYGlIABc1EBgYIk06TZU6odUZNXPYsDqIK2J4rsymcZvWzfbPl8rEzzqdE0O/NsKq/6M7EiMlrzqEcwKg5JMR0n8NKLyeAeye/4NKfiflW67WzU=
