INSERT INTO JOBS VALUES(1, 'DIRECTOR');
INSERT INTO JOBS VALUES(2, 'MANAGER');
INSERT INTO JOBS VALUES(3, 'COOK');
INSERT INTO JOBS VALUES(4, 'COOK_ASSISTANT');
INSERT INTO JOBS VALUES(5, 'HEAD_WAITER');
INSERT INTO JOBS VALUES(6, 'WAITER');
INSERT INTO JOBS VALUES(7, 'CLEANER');
INSERT INTO JOBS VALUES(8, 'SECURITY');