
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('White', 'Davis', '1965-06-20', 1, 90000.0, 'Employee');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Black', 'Sarah', '1975-09-10', 2, 75000.0, 'Employee');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Green', 'Piter', '1980-10-05', 3, 60000.0, 'Cook');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Brown', 'Steven', '1985-08-08', 4, 50000.0, 'Cook');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Gray', 'Stew', '1990-09-10', 6, 40000.0, 'Waiter');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Orange', 'John', '1995-10-23', 6, 40000.0, 'Waiter');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Red', 'Marion', '1997-11-25', 7, 30000.0, 'Employee');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Wright', 'Clif', '1998-07-20', 7, 30000.0, 'Employee');
INSERT INTO EMPLOYEE (surname, name, birthday, position_id, salary, dtype) VALUES('Blue', 'Stew', '1999-10-15', 6, 35000.0, 'Waiter');


INSERT INTO INGREDIENT (name, amount) VALUES('potato', 10000);
INSERT INTO INGREDIENT (name, amount) VALUES('beef', 7000);
INSERT INTO INGREDIENT (name, amount) VALUES('chicken egg', 50);
INSERT INTO INGREDIENT (name, amount) VALUES('butter', 3000);
INSERT INTO INGREDIENT (name, amount) VALUES('sunflower oil', 8000);
INSERT INTO INGREDIENT (name, amount) VALUES('salt', 1500);
INSERT INTO INGREDIENT (name, amount) VALUES('chicken', 10000);
INSERT INTO INGREDIENT (name, amount) VALUES('pasta', 7000);
INSERT INTO INGREDIENT (name, amount) VALUES('water', 25000);
INSERT INTO INGREDIENT (name, amount) VALUES('dill', 700);
INSERT INTO INGREDIENT (name, amount) VALUES('parsley', 600);
INSERT INTO INGREDIENT (name, amount) VALUES('onion', 5000);
INSERT INTO INGREDIENT (name, amount) VALUES('flour', 10000);
INSERT INTO INGREDIENT (name, amount) VALUES('sour cream', 3000);
INSERT INTO INGREDIENT (name, amount) VALUES('tomato paste', 700);
INSERT INTO INGREDIENT (name, amount) VALUES('lettuce', 700);
INSERT INTO INGREDIENT (name, amount) VALUES('cabbage', 6000);
INSERT INTO INGREDIENT (name, amount) VALUES('tomato', 10000);
INSERT INTO INGREDIENT (name, amount) VALUES('cucumber', 7000);
INSERT INTO INGREDIENT (name, amount) VALUES('basil', 600);
INSERT INTO INGREDIENT (name, amount) VALUES('sesame', 300);
INSERT INTO INGREDIENT (name, amount) VALUES('carrots', 7000);
INSERT INTO INGREDIENT (name, amount) VALUES('mayonnaise', 5000);
INSERT INTO INGREDIENT (name, amount) VALUES('rice', 10000);


INSERT INTO DISH (name, description, cost, weight) VALUES('steak', 'nutritious dish, rich in protein', 65, 400);
INSERT INTO DISH (name, description, cost, weight) VALUES('chicken broth', 'first dish', 30, 300);
INSERT INTO DISH (name, description, cost, weight) VALUES('beef Stroganoff', 'meat dish on the classic recipe', 80, 350);
INSERT INTO DISH (name, description, cost, weight) VALUES('fries', 'fried potato', 30, 350);
INSERT INTO DISH (name, description, cost, weight) VALUES('spring breeze salad', 'light salad with delicious vegetables', 55, 250);
INSERT INTO DISH (name, description, cost, weight) VALUES('olivier', 'salad on the classic recipe', 65, 400);
INSERT INTO DISH (name, description, cost, weight) VALUES('soup', 'potato soup', 45, 300);
INSERT INTO DISH (name, description, cost, weight) VALUES('plov', 'rice with meat', 55, 300);


INSERT INTO MENU VALUES(1, 'summer');
INSERT INTO MENU VALUES(2, 'winter');
INSERT INTO MENU VALUES(3, 'spring');
INSERT INTO MENU VALUES(4, 'autumn');


INSERT INTO DISH_TO_MENU VALUES(1, 2);
INSERT INTO DISH_TO_MENU VALUES(1, 3);
INSERT INTO DISH_TO_MENU VALUES(1, 4);
INSERT INTO DISH_TO_MENU VALUES(1, 5);

INSERT INTO DISH_TO_MENU VALUES(2, 1);
INSERT INTO DISH_TO_MENU VALUES(2, 2);
INSERT INTO DISH_TO_MENU VALUES(2, 4);
INSERT INTO DISH_TO_MENU VALUES(2, 6);

INSERT INTO DISH_TO_MENU VALUES(3, 1);
INSERT INTO DISH_TO_MENU VALUES(3, 2);
INSERT INTO DISH_TO_MENU VALUES(3, 4);

INSERT INTO DISH_TO_MENU VALUES(4, 1);
INSERT INTO DISH_TO_MENU VALUES(4, 8);


INSERT INTO INGREDIENT_TO_DISH VALUES(1, 1, 1, 300);
INSERT INTO INGREDIENT_TO_DISH VALUES(2, 1, 2, 200);
INSERT INTO INGREDIENT_TO_DISH VALUES(3, 1, 3, 1);
INSERT INTO INGREDIENT_TO_DISH VALUES(4, 1, 4, 30);
INSERT INTO INGREDIENT_TO_DISH VALUES(5, 1, 5, 20);
INSERT INTO INGREDIENT_TO_DISH VALUES(6, 1, 6, 10);

INSERT INTO INGREDIENT_TO_DISH VALUES(7, 2, 7, 300);
INSERT INTO INGREDIENT_TO_DISH VALUES(8, 2, 8, 50);
INSERT INTO INGREDIENT_TO_DISH VALUES(9, 2, 9, 200);
INSERT INTO INGREDIENT_TO_DISH VALUES(10, 2, 10, 10);
INSERT INTO INGREDIENT_TO_DISH VALUES(11, 2, 11, 10);
INSERT INTO INGREDIENT_TO_DISH VALUES(12, 2, 6, 5);

INSERT INTO INGREDIENT_TO_DISH VALUES(13, 3, 2, 400);
INSERT INTO INGREDIENT_TO_DISH VALUES(14, 3, 12, 100);
INSERT INTO INGREDIENT_TO_DISH VALUES(15, 3, 13, 25);
INSERT INTO INGREDIENT_TO_DISH VALUES(16, 3, 14, 30);
INSERT INTO INGREDIENT_TO_DISH VALUES(17, 3, 15, 30);
INSERT INTO INGREDIENT_TO_DISH VALUES(18, 3, 5, 50);
INSERT INTO INGREDIENT_TO_DISH VALUES(19, 3, 6, 5);

INSERT INTO INGREDIENT_TO_DISH VALUES(20, 4, 1, 300);
INSERT INTO INGREDIENT_TO_DISH VALUES(21, 4, 6, 10);
INSERT INTO INGREDIENT_TO_DISH VALUES(22, 4, 5, 500);

INSERT INTO INGREDIENT_TO_DISH VALUES(23, 5, 16, 100);
INSERT INTO INGREDIENT_TO_DISH VALUES(24, 5, 17, 50);
INSERT INTO INGREDIENT_TO_DISH VALUES(25, 5, 18, 50);
INSERT INTO INGREDIENT_TO_DISH VALUES(26, 5, 19, 50);
INSERT INTO INGREDIENT_TO_DISH VALUES(27, 5, 20, 20);
INSERT INTO INGREDIENT_TO_DISH VALUES(28, 5, 5, 30);
INSERT INTO INGREDIENT_TO_DISH VALUES(29, 5, 6, 5);
INSERT INTO INGREDIENT_TO_DISH VALUES(30, 5, 21, 5);

INSERT INTO INGREDIENT_TO_DISH VALUES(31, 6, 1, 60);
INSERT INTO INGREDIENT_TO_DISH VALUES(32, 6, 7, 60);
INSERT INTO INGREDIENT_TO_DISH VALUES(33, 6, 3, 1);
INSERT INTO INGREDIENT_TO_DISH VALUES(34, 6, 19, 60);
INSERT INTO INGREDIENT_TO_DISH VALUES(35, 6, 22, 40);
INSERT INTO INGREDIENT_TO_DISH VALUES(36, 6, 23, 20);
INSERT INTO INGREDIENT_TO_DISH VALUES(37, 6, 6, 5);

INSERT INTO INGREDIENT_TO_DISH VALUES(38, 7, 1, 150);
INSERT INTO INGREDIENT_TO_DISH VALUES(39, 7, 6, 15);
INSERT INTO INGREDIENT_TO_DISH VALUES(40, 7, 9, 150);

INSERT INTO INGREDIENT_TO_DISH VALUES(41, 8, 2, 150);
INSERT INTO INGREDIENT_TO_DISH VALUES(42, 8, 6, 10);
INSERT INTO INGREDIENT_TO_DISH VALUES(43, 8, 24, 50);


INSERT INTO ORDERS VALUES(1, 5, 2, '2015-07-01', TRUE);
INSERT INTO ORDERS VALUES(2, 5, 3, '2015-07-02', TRUE);
INSERT INTO ORDERS VALUES(3, 6, 1, '2015-07-02', TRUE);
INSERT INTO ORDERS VALUES(4, 5, 4, '2015-07-03', FALSE);
INSERT INTO ORDERS VALUES(5, 6, 2, '2015-07-03', TRUE);
INSERT INTO ORDERS VALUES(6, 6, 3, '2015-07-04', FALSE);
INSERT INTO ORDERS VALUES(7, 9, 5, '2015-07-05', FALSE);


INSERT INTO DISH_TO_ORDERS VALUES(1, 1);
INSERT INTO DISH_TO_ORDERS VALUES(1, 2);
INSERT INTO DISH_TO_ORDERS VALUES(1, 3);

INSERT INTO DISH_TO_ORDERS VALUES(2, 2);
INSERT INTO DISH_TO_ORDERS VALUES(2, 4);
INSERT INTO DISH_TO_ORDERS VALUES(2, 5);
INSERT INTO DISH_TO_ORDERS VALUES(2, 6);

INSERT INTO DISH_TO_ORDERS VALUES(3, 2);
INSERT INTO DISH_TO_ORDERS VALUES(3, 3);
INSERT INTO DISH_TO_ORDERS VALUES(3, 4);

INSERT INTO DISH_TO_ORDERS VALUES(4, 4);
INSERT INTO DISH_TO_ORDERS VALUES(4, 5);

INSERT INTO DISH_TO_ORDERS VALUES(5, 4);
INSERT INTO DISH_TO_ORDERS VALUES(5, 6);

INSERT INTO DISH_TO_ORDERS VALUES(6, 3);
INSERT INTO DISH_TO_ORDERS VALUES(6, 4);
INSERT INTO DISH_TO_ORDERS VALUES(6, 5);
INSERT INTO DISH_TO_ORDERS VALUES(6, 6);

INSERT INTO DISH_TO_ORDERS VALUES(7, 1);
INSERT INTO DISH_TO_ORDERS VALUES(7, 5);
INSERT INTO DISH_TO_ORDERS VALUES(7, 7);
INSERT INTO DISH_TO_ORDERS VALUES(7, 8);


INSERT INTO COOKED_DISH VALUES(1, 1, 1, 3);
INSERT INTO COOKED_DISH VALUES(2, 1, 2, 3);
INSERT INTO COOKED_DISH VALUES(3, 1, 3, 3);

INSERT INTO COOKED_DISH VALUES(4, 2, 2, 3);
INSERT INTO COOKED_DISH VALUES(5, 2, 4, 3);
INSERT INTO COOKED_DISH VALUES(6, 2, 5, 3);
INSERT INTO COOKED_DISH VALUES(7, 2, 6, 3);

INSERT INTO COOKED_DISH VALUES(8, 3, 3, 4);
INSERT INTO COOKED_DISH VALUES(9, 3, 4, 4);

INSERT INTO COOKED_DISH VALUES(10, 4, 4, 4);
INSERT INTO COOKED_DISH VALUES(11, 4, 2, 4);
INSERT INTO COOKED_DISH VALUES(12, 4, 4, 4);
INSERT INTO COOKED_DISH VALUES(13, 4, 5, 4);

INSERT INTO COOKED_DISH VALUES(14, 5, 3, 4);
INSERT INTO COOKED_DISH VALUES(15, 5, 4, 4);
INSERT INTO COOKED_DISH VALUES(16, 5, 5, 4);
INSERT INTO COOKED_DISH VALUES(17, 5, 6, 4);

INSERT INTO COOKED_DISH VALUES(18, 6, 1, 3);
INSERT INTO COOKED_DISH VALUES(19, 6, 4, 3);
INSERT INTO COOKED_DISH VALUES(20, 6, 6, 3);

INSERT INTO COOKED_DISH VALUES(21, 7, 2, 3);
INSERT INTO COOKED_DISH VALUES(22, 7, 3, 3);





