CREATE TABLE JOBS(
  id INT PRIMARY KEY NOT NULL,
  position VARCHAR(20)
);

CREATE TABLE EMPLOYEE(
  id INT PRIMARY KEY NOT NULL,
  surname VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  birthday DATE NOT NULL,
  position_id INT REFERENCES JOBS(id),
  salary REAL,
  dtype CHARACTER VARYING
);