
SELECT EMPLOYEE.surname, EMPLOYEE.name, JOBS.position, EMPLOYEE.birthday, EMPLOYEE.salary
FROM EMPLOYEE INNER JOIN JOBS ON EMPLOYEE.position_id = JOBS.id;


SELECT INGREDIENT.id, INGREDIENT.name, STORAGE.amount
FROM INGREDIENT INNER JOIN STORAGE ON INGREDIENT.id = STORAGE.ingredient_id;


SELECT DISH_TO_MENU.id, DISH_TO_MENU.menu_id, MENU.name, DISH_TO_MENU.dish_id, DISH.name
FROM (DISH_TO_MENU INNER JOIN DISH ON DISH_TO_MENU.dish_id = DISH.id)
  INNER JOIN MENU ON DISH_TO_MENU.menu_id = MENU.id;


SELECT INGREDIENT_TO_DISH.id, DISH.id AS dish_id, DISH.name, INGREDIENT.id AS ingredient_id, INGREDIENT.name,
  INGREDIENT_TO_DISH.weight
FROM (INGREDIENT_TO_DISH INNER JOIN DISH ON INGREDIENT_TO_DISH.dish_id = DISH.id)
  INNER JOIN INGREDIENT ON INGREDIENT_TO_DISH.ingredient_id = INGREDIENT.id;


SELECT ORDERING.id, ORDERING.employee_id, EMPLOYEE.name, EMPLOYEE.surname, JOBS.position, ORDERING.date
FROM (ORDERING INNER JOIN EMPLOYEE ON ORDERING.employee_id = EMPLOYEE.id)
  INNER JOIN JOBS ON EMPLOYEE.position_id = JOBS.id;


SELECT DISH_TO_ORDERING.id, ORDERING.id AS order_id, ORDERING.table_number, ORDERING.date,
                            EMPLOYEE.surname AS waiter_surname, EMPLOYEE.name AS waiter_name, JOBS.position, DISH.ID AS dish_id, DISH.name AS dish_name
FROM (((DISH_TO_ORDERING INNER JOIN ORDERING ON DISH_TO_ORDERING.order_id = ORDERING.id)
        INNER JOIN DISH ON DISH_TO_ORDERING.dish_id = DISH.id)
  INNER JOIN EMPLOYEE ON ORDERING.employee_id = EMPLOYEE.id)
  INNER JOIN JOBS ON EMPLOYEE.position_id = JOBS.id;


SELECT COOKED_DISH.id, ORDERING.id AS order_id, ORDERING.table_number, ORDERING.date, DISH.id AS dish_id,
                       DISH.name AS dish_name, EMPLOYEE.surname AS cook_surname, EMPLOYEE.name AS cook_name, JOBS.position
FROM ((((COOKED_DISH INNER JOIN DISH_TO_ORDERING ON COOKED_DISH.ordered_dish_id = DISH_TO_ORDERING.id)
         INNER JOIN ORDERING ON DISH_TO_ORDERING.order_id = ORDERING.id)
        INNER JOIN DISH ON DISH_TO_ORDERING.dish_id = DISH.id)
  INNER JOIN EMPLOYEE ON COOKED_DISH.cook_id = EMPLOYEE.id)
  INNER JOIN JOBS ON EMPLOYEE.position_id = JOBS.id;