DROP TABLE Cooked_dish;
DROP TABLE Dish_to_orders;
DROP TABLE Orders;
DROP TABLE Employee;
DROP TABLE Jobs;
DROP TABLE Dish_to_menu;
DROP TABLE Menu;
DROP TABLE Ingredient_to_dish;
DROP TABLE Dish;
DROP TABLE Ingredient;

DROP SEQUENCE employee_id;
DROP SEQUENCE dish_id;
DROP SEQUENCE ingr_to_dish_id;
DROP SEQUENCE ingredient_id;
DROP SEQUENCE jobs_id;
DROP SEQUENCE menu_id;
DROP SEQUENCE orders_id;
DROP SEQUENCE cooked_dish_id;